# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDingDong' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDingDong

  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'TextFieldEffects'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'ObjectMapper', '~> 3.2'
  pod 'Firebase/Messaging'
  pod 'Alamofire', '~> 4.5'
  pod 'Kingfisher', '~> 5.0'
  pod 'BEMCheckBox'
  pod 'GoogleSignIn'
  pod 'SnapKit', '~> 4.0.0'


end
